database:
    image: postgres:9.4
    ports:
        - "5432:5432"

redis:
    image: redis:3.0-alpine
    ports:
        - "6379:6379"

router:
    image: nginx
    ports:
        - "80:80"
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    links:
        - api
        - fe
        - mailer

api:
    image: yuda/api:latest
    command: --reload
    volumes:
        - ./api:/app
    links:
        - database
        - mailer

fe:
    image: yuda/fe:latest
    command: -c /etc/nginx/nginx-dev.conf

mailer:
    image: yuda/mailer:latest
    volumes:
        - ./mailer:/app
    ports:
        - "3000:3000"
    links:
        - database
        - redis

mailerworker:
    image: yuda/mailer:latest
    command: bin/rake resque:work
    volumes:
        - ./mailer:/app
    links:
        - database
        - redis
