kind: Service
apiVersion: v1
metadata:
    name: database
spec:
    ports:
        - port: 5432

---

kind: Endpoints
apiVersion: v1
metadata:
  name: database
subsets:
  - addresses:
        - ip: 172.20.0.126 # <-- RDS instance IP
    ports:
        - port: 5432
